export const Users = [
  {
    id: 0,
    name: "kim",
    userId: "kim",
    password: "1234",
    img: "/img/profile/11.jpg",
    content: "user 0 안녕하세요 1",
  },
  {
    id: 1,
    name: "park",
    userId: "park",
    password: "1234",
    img: "/img/profile/22.jpg",
    content: "user 0 안녕하세요2",
  },
  {
    id: 2,
    name: "lee",
    userId: "lee",
    password: "1234",
    img: "/img/profile/33.jpg",
    content: "user 0 안녕하세요 3",
  },
  {
    id: 3,
    name: "zee",
    userId: "zee",
    password: "1234",
    content: "user 0 안녕하세요 4",
  },
  {
    id: 4,
    name: "qee",
    userId: "qee",
    password: "1234",
    content: "user 0 안녕하세요 5",
  },
];
