server:
  port: 9001

spring:
  application:
    name: discovery-client2

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
