server:
  port: 9000

spring:
  application:
    name: discovery-client1

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.10:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, shutdown, startup